name: First Workflow
on: push 
env:
  name: "raghav"
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
       - name: Code Checkout
         uses: actions/checkout@v4
       - name: Node Js Installation
         uses: actions/setup-node@v4
         with:
           node-version: 18.0
       - name: Install Dependencies
         run: npm install
       - name: Testing 
         run: npm run test
       - name: Just printing
         run: echo $name 
       - name: Printing Secret
         run: echo "${{ secrets.PASSWORD }}"
  Build:
    needs: Testing
    runs-on: ubuntu-latest
    steps:
       - name: Code Checkout
         uses: actions/checkout@v4
       - name: Node Js Installation
         uses: actions/setup-node@v4
         with:
           node-version: 18.0
       - name: Install Dependencies
         run: npm install
       - name: Creating a Build
         run: npm run build
       - name: showing file structure
         run: ls
       - name: Uploading Artificats
         uses: actions/upload-artifact@v4
         with:
          name: My-Artifacts
          path: |
            dist/spring-boot-initial-0.0.1-SNAPSHOT.jar
        
