name: First Workflow
on: push 
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
       - name: Code Checkout
         uses: actions/checkout@v4
       - name: Node Js Installation
         uses: actions/setup-node@v4
         with:
           node-version: 18.0
       - name: Install Dependencies
         run: npm install
       - name: Testing 
         run: npm run test
  Build:
    needs: Testing
    runs-on: ubuntu-latest
    steps:
       - name: Code Checkout
         uses: actions/checkout@v4
       - name: Node Js Installation
         uses: actions/setup-node@v4
         with:
           node-version: 18.0
       - name: Install Dependencies
         run: npm install
       - name: Creating a Build
         run: npm run build
       - name: showing file structure
         run: ls

        
